language: rust
rust: stable
addons:
  apt:
    packages:
      - libglib2.0-dev
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcapstone-dev
  - ./travis/install_unicorn.sh

