language: rust
rust: stable
sudo: required
cache:
  directories:
    - unicorn
    - capstone
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install clang gcc
  - ./travis/unicorn.sh
  - ./travis/capstone.sh

before_script:
  - make -C tests/candidates
