language: rust
rust: stable
sudo: false
cache:
  directories:
    - unicorn
    - capstone
before_install:
  - ./travis/unicorn.sh
  - ./travis/capstone.sh
  - LD_LIBRARY_PATH=$PWD/unicorn/:$PWD/capstone/:$LD_LIBRARY_PATH
