all:
	gcc -fno-builtin -fno-inline-small-functions -static -Wall stdlib.c -o ../../candidates/stdlib
	g++ -fno-builtin -fno-inline-small-functions -static -Wall std_string.cpp -o ../../candidates/std_string
